### PR TITLE
docs: add provenance example to README.md

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Curious why the `ref_type` is empty.

**Comment by laurentsimon** [comment]
well, I forgot to add it :-)

**Comment by laurentsimon** [comment]
Maybe add "ref_type: branch" before merging. I'm sending a PR to fix the code

**Comment by asraa** [comment]
Added ref_type!

**Pull request merged**
